"use client"

import { useState } from "react"
import type { components } from "@/lib/api/schema"

type Event = components["schemas"]["EventResponse"]

type Props = {
  event: Event
  bannerUrl?: string
  variant?: number
  className?: string
  showFallbackTitle?: boolean
}

export function EventArtwork({
  event,
  bannerUrl,
  variant = 0,
  className = "",
  showFallbackTitle = true,
}: Props) {
  const [failedUrl, setFailedUrl] = useState<string>()
  const artClass =
    variant % 3 === 1 ? "nightline-art--sport" : variant % 3 === 2 ? "nightline-art--culture" : ""

  return (
    <div className={"nightline-art " + artClass + " " + className}>
      {bannerUrl && failedUrl !== bannerUrl ? (
        // Presigned media URLs are generated by the backend and cannot use a fixed Next image host.
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={bannerUrl}
          alt=""
          onError={() => setFailedUrl(bannerUrl)}
          className="absolute inset-0 z-10 size-full object-cover"
        />
      ) : showFallbackTitle ? (
        <span className="absolute bottom-5 left-5 right-5 z-10 line-clamp-2 text-xl font-bold uppercase tracking-tight leading-tight text-white drop-shadow-lg sm:text-2xl">
          {event.name || "SmartEvent"}
        </span>
      ) : null}
    </div>
  )
}
