import type { components } from "@/lib/api/schema"

type Event = components["schemas"]["EventResponse"]

type Props = {
  event: Event
  bannerUrl?: string
  variant?: number
  className?: string
  showFallbackTitle?: boolean
}

export function EventArtwork({
  event,
  bannerUrl,
  variant = 0,
  className = "",
  showFallbackTitle = true,
}: Props) {
  const artClass =
    variant % 3 === 1 ? "nightline-art--sport" : variant % 3 === 2 ? "nightline-art--culture" : ""

  return (
    <div className={"nightline-art " + artClass + " " + className}>
      {bannerUrl ? (
        // Presigned media URLs are generated by the backend and cannot use a fixed Next image host.
        // eslint-disable-next-line @next/next/no-img-element
        <img src={bannerUrl} alt="" className="absolute inset-0 z-10 size-full object-cover" />
      ) : showFallbackTitle ? (
        <span className="absolute bottom-5 left-5 right-5 z-10 line-clamp-2 text-2xl sm:text-3xl font-black uppercase tracking-[-0.08em] leading-[0.95] text-white drop-shadow-lg">
          {event.name || "SmartEvent"}
        </span>
      ) : null}
    </div>
  )
}
